version: '3.4'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"