version: '3.4'

services:
  # node-microservice:
  #   build: .
  #   depends_on:
  #     - nats
  #     - mongodb
  #   environment:
  #     - DB_HOST=mongodb
  #     - PUBSUB_SERVERS=nats
  #     - PUBSUB_PORT=4222
  http-nats-proxy:
    image: wshaddix/http-nats-proxy:1.0.4
    depends_on:
      - nats
    ports:
      - "5000:5000"
    environment:
      - HTTP_NATS_PROXY_HOST_PORT=5000
      - HTTP_NATS_PROXY_NAT_URL=nats://nats:4222
      - HTTP_NATS_PROXY_WAIT_TIMEOUT_SECONDS=10
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  nats:
    image: nats:latest
    ports:
      - "8222:8222"
      - "6222:6222"
      - "4222:4222"